### ISSUE TITLE
Trabajo remoto, mitos y realidades

### ISSUE THREAD

**Issue by crysfel** [javascriptecuador/Meetups#5]
> Nuestros eventos se rigen por nuestro código de conducta [https://github.com/javascriptecuador/.github/blob/master/CODE_OF_CONDUCT.md]

## Dirección de Correo electrónico
crysfel@bleext.com

## Nombre Completo
Crysfel Villa

## Usuario de twitter
@crysfel

## ¿Qué tipo de evento quieres proponer?

- [ ] Charla
- [x] Taller
- [ ] Post
- [ ] Charla y taller (del mismo tema)

## ¿Lugar de la charla?

online

## Título de la charla

Trabajo remoto, mitos y realidades

## Duración Aproximada

25 min

## Breve descripción de la charla/taller/post
En esta charla se planea mostrar los mitos y realidades sobre el trabajo remoto, maneras efectivas de ser productivo en un ambiente dirigido por objetivos, como mantener una buena comunicación con tu equipo remoto, expectativas y realidades sobre lo que verdaderamente es trabajar de menera remota.

## Breve descripción sobre usted 

Soy un Ingeniero de Software con más de 12 años de experiencia. He dirigido equipos en diferentes países como USA, Japón, España, India y trabajado con cientos de ingenieros al rededor del mundo de manera remota por los últimos 10 años. He publicado dos libros y entrenado equipos en JavaScript.

## ¿Representas alguna compañía o empresa?
Coding Coach (http://codingcoach.io)

## ¿Quieres agregar algo más?

----------------
> Muchas gracias!
> Comunidad de Javascript Ecuador.

**Comment by rpalaciosg** [comment]
Hola @crysfel Muchas Gracias y Felicidades por postular tu charla 🎉, seguiremos en contacto para cordinar cualquier cosa que haga falta. Espero hayas pasado muy bonito en union de tu familia, y una Feliz Navidad si es que lo celebras.

**Comment by LuisReinoso** [comment]
Oww! Gracias  @crysfel !
